# Docs
# ----
# General Docs:    https://docs.helix-editor.com/
# Wiki:            https://github.com/helix-editor/helix/wiki
# LSP Docs:        https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers

theme = "github_dark"

[editor]
true-color = true
mouse = true
bufferline = "multiple"

[keys.normal]
G = "goto_file_end"
X = "extend_line_above"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
q = ":quit"
w = ":write"
l = ":config-reload"

# [editor.cursor-shape]
# insert = "bar"
# normal = "block"
# select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
