"__   _(_)_ __ ___  _ __ ___ "
"\ \ / / | '_ ` _ \| '__/ __|"
" \ V /| | | | | | | | | (__ "
"  \_/ |_|_| |_| |_|_|  \___|"

source ~/.vim/settings.vim
source ~/.vim/plugins.vim
source ~/.vim/functions.vim
source ~/.vim/commands.vim
source ~/.vim/keybinds.vim
source ~/.vim/colorschemes.vim
source ~/.vim/autocmds.vim
source ~/.config/vimrc
